package rig

import (
	"fmt"
	"path/filepath"
	"sort"
	"strings"
)

// The generated helper files that sit alongside go.work in a rig root.
const (
	EnvShName     = "env.sh"
	EnvrcName     = ".envrc"
	ClaudeMDName  = "CLAUDE.md"
	ReadmeName    = "README.md"
	GitignoreName = ".gitignore"
)

// GeneratedFile is one file written into a rig root beside the manifest.
type GeneratedFile struct {
	// Name is the path relative to the rig root.
	Name string
	// Content is the whole file.
	Content string
	// Mode is the file mode; 0 means 0o644.
	Mode uint32
}

// GeneratedFiles renders every helper file for a rig.
//
// rigRoot must be absolute: env.sh exports GOWORK, and Go rejects a relative
// GOWORK outright, so a relative root would produce a file that breaks every
// `go` command the moment it is sourced.
func GeneratedFiles(m *Manifest, rigRoot string) []GeneratedFile {
	return []GeneratedFile{
		{Name: EnvShName, Content: renderEnvSh(m, rigRoot), Mode: 0o755},
		{Name: EnvrcName, Content: renderEnvrc()},
		{Name: ClaudeMDName, Content: renderClaudeMD(m, rigRoot)},
		{Name: ReadmeName, Content: renderReadme(m, rigRoot)},
		{Name: GitignoreName, Content: renderGitignore()},
	}
}

// goWorkPath is the absolute path of the generated workspace file.
func goWorkPath(rigRoot string) string { return filepath.Join(rigRoot, GoWorkName) }

// renderEnvSh writes the shell exports that point a session at this rig.
//
// GOWORK is absolute because Go resolves it relative to nothing: a relative
// value is rejected, and the whole point of the file is that `go` behaves the
// same from any directory inside the rig.
func renderEnvSh(m *Manifest, rigRoot string) string {
	var b strings.Builder
	b.WriteString("#!/bin/sh\n")
	b.WriteString("# Generated by `wgo rig` — do not edit; `wgo rig sync` rewrites it.\n")
	fmt.Fprintf(&b, "# Point this shell at the %s rig:\n", m.Name)
	fmt.Fprintf(&b, "#   . %s\n", filepath.Join(rigRoot, EnvShName))
	b.WriteString("#\n")
	b.WriteString("# GOWORK is absolute on purpose. Go rejects a relative GOWORK, and the\n")
	b.WriteString("# checkouts below ship their own go.work files that Go's upward search\n")
	b.WriteString("# would otherwise find first.\n")
	fmt.Fprintf(&b, "GOWORK=%s\n", shellQuote(goWorkPath(rigRoot)))
	b.WriteString("export GOWORK\n")
	fmt.Fprintf(&b, "WGO_RIG=%s\n", shellQuote(m.Name))
	b.WriteString("export WGO_RIG\n")
	return b.String()
}

// renderEnvrc defers to env.sh so direnv and a plain shell cannot disagree
// about what the rig's environment is.
func renderEnvrc() string {
	return "# Generated by `wgo rig` — do not edit; `wgo rig sync` rewrites it.\n" +
		"# direnv entrypoint. The exports live in env.sh so `direnv allow` and a\n" +
		"# manually sourced shell get byte-identical environments.\n" +
		"source_env_if_exists " + EnvShName + "\n"
}

// renderGitignore keeps a rig out of version control.
//
// A rig is disposable, derived, and can run to hundreds of megabytes of
// checkouts. It is also frequently created inside a directory the user already
// tracks, so the safe default is to ignore the whole thing.
func renderGitignore() string {
	return "# Generated by `wgo rig` — do not edit; `wgo rig sync` rewrites it.\n" +
		"# A rig is derived, disposable and large. Nothing here belongs in git;\n" +
		"# rig.toml is the only state, and `wgo rig new` can rebuild it.\n" +
		"*\n"
}

// renderReadme explains the rig to a human who found the directory.
func renderReadme(m *Manifest, rigRoot string) string {
	var b strings.Builder
	fmt.Fprintf(&b, "# rig: %s\n\n", m.Name)
	b.WriteString("Generated by `wgo rig`. This directory is a **pinned, disposable Go\n")
	b.WriteString("workspace**: one editable checkout per module the artifact below depends\n")
	b.WriteString("on, each fixed at the commit that artifact shipped with.\n\n")

	if src := sourceSummary(m.Source); src != "" {
		fmt.Fprintf(&b, "- **Reproducing:** `%s`\n", src)
	}
	fmt.Fprintf(&b, "- **Primary module:** `%s`\n", m.Primary)
	fmt.Fprintf(&b, "- **Checkouts:** %d, serving %d modules\n", len(m.Checkouts), len(m.Members))
	if m.Created != "" {
		fmt.Fprintf(&b, "- **Created:** %s\n", m.Created)
	}

	b.WriteString("\n## Using it\n\n")
	b.WriteString("```sh\n")
	fmt.Fprintf(&b, ". %s\n", filepath.Join(rigRoot, EnvShName))
	b.WriteString("go build ./...\n")
	b.WriteString("```\n\n")
	b.WriteString("Every `go` command needs `GOWORK` set to this rig's `go.work`. The\n")
	b.WriteString("checkouts ship their own `go.work` files, and Go's upward search would\n")
	b.WriteString("find one of those first.\n")

	b.WriteString("\n## Do not run these here\n\n")
	b.WriteString("| Command | Why |\n|---|---|\n")
	b.WriteString("| `go mod tidy` | Rewrites a pinned checkout's `go.mod`, destroying the pin. |\n")
	b.WriteString("| `go work sync` | Writes the workspace build list into *every* member's `go.mod` at once. |\n")
	b.WriteString("| `jj bookmark set` | Rig checkouts carry no bookmark by design; see below. |\n")

	b.WriteString("\n## Checkouts\n\n")
	b.WriteString("| Directory | Repo | Pin | Contents |\n|---|---|---|---|\n")
	for _, c := range m.Checkouts {
		fmt.Fprintf(&b, "| `%s` | `%s` | `%s` | %s |\n",
			c.Dir, c.Repo, pinLabel(c), contentsLabel(c))
	}

	if len(m.Skipped) > 0 {
		b.WriteString("\n## Skipped\n\n")
		b.WriteString("These modules got no checkout and are served from the module cache.\n\n")
		b.WriteString("| Module | Why |\n|---|---|\n")
		for _, s := range m.Skipped {
			fmt.Fprintf(&b, "| `%s` | %s |\n", s.Path, s.String())
		}
	}

	b.WriteString("\n## Making a change into a PR\n\n")
	b.WriteString("You cannot, from here. Rig checkouts are pinned to released tags and\n")
	b.WriteString("carry no bookmark, so there is nothing to push. Reproduce the fix in a\n")
	b.WriteString("normal worktree — `wgo to <branch>` — and land it there.\n")

	b.WriteString("\nRemove this rig with `wgo rig rm " + m.Name + "`, which also forgets the\n")
	b.WriteString("jj workspaces it registered in each main clone. Deleting the directory by\n")
	b.WriteString("hand leaves those workspaces behind.\n")
	return b.String()
}

// renderClaudeMD orients a coding agent that opens the rig.
//
// The emphasis differs from README.md on purpose: an agent's most likely
// failure here is to treat the rig as an ordinary checkout and "helpfully" run
// `go mod tidy` or commit a fix, both of which destroy what the rig is for.
func renderClaudeMD(m *Manifest, rigRoot string) string {
	var b strings.Builder
	b.WriteString("# CLAUDE.md\n\n")
	b.WriteString("Generated by `wgo rig`. Read this before running anything here.\n\n")

	b.WriteString("## What this directory is\n\n")
	fmt.Fprintf(&b, "A **rig** named `%s`: a pinned, disposable Go workspace that reproduces\n", m.Name)
	if src := sourceSummary(m.Source); src != "" {
		fmt.Fprintf(&b, "`%s` from source.\n", src)
	} else {
		fmt.Fprintf(&b, "`%s` from source.\n", m.Primary)
	}
	b.WriteString("\nEach directory under `src/` is a **jj workspace pinned to a released\n")
	b.WriteString("commit**, not a branch checkout. Most are *sparse*: only the module's own\n")
	b.WriteString("subdirectory is materialised, so a missing file is usually expected\n")
	b.WriteString("rather than a broken checkout.\n\n")
	b.WriteString("It exists to attach a debugger to a shipped artifact and reproduce a\n")
	b.WriteString("customer issue against the exact code that shipped.\n")

	b.WriteString("\n## Always set GOWORK\n\n")
	b.WriteString("```sh\n")
	fmt.Fprintf(&b, "export GOWORK=%s\n", goWorkPath(rigRoot))
	b.WriteString("```\n\n")
	b.WriteString("Or `. env.sh`. This is not optional and not a convenience. Several\n")
	b.WriteString("checkouts ship their own committed `go.work`, and Go finds a workspace by\n")
	b.WriteString("walking *up* from the working directory — so a bare `go build` inside a\n")
	b.WriteString("checkout silently answers for that repo's workspace instead of the rig's,\n")
	b.WriteString("and succeeds while doing it.\n")

	b.WriteString("\n## Never run these\n\n")
	b.WriteString("- **`go mod tidy`** — rewrites the pinned `go.mod` of whichever checkout\n")
	b.WriteString("  you are in. The pin is the entire value of the rig.\n")
	b.WriteString("- **`go work sync`** — writes the workspace's resolved build list back\n")
	b.WriteString("  into *every* member's `go.mod` at once, replacing the versions the\n")
	b.WriteString("  artifact shipped with. It dirties all of them in one command.\n")
	b.WriteString("- **`jj bookmark set` / `jj git push`** — these checkouts are pinned to\n")
	b.WriteString("  tags and deliberately carry no bookmark. There is no branch to push.\n")
	b.WriteString("- **`git` anything** — wgo uses jj. The checkouts are jj workspaces\n")
	b.WriteString("  sharing one `.jj/repo` per main clone.\n")

	b.WriteString("\n## Editing is fine\n\n")
	b.WriteString("`-r <commit>` makes the pinned commit the working copy's **parent**, so\n")
	b.WriteString("the content matches the tag and your edits land in a fresh child change.\n")
	b.WriteString("Edit freely, set breakpoints, rebuild. You are not disturbing the pin.\n\n")
	b.WriteString("To turn a fix into a PR, do **not** try to push from here. Reproduce it\n")
	b.WriteString("in a normal worktree (`wgo to <branch>`) and land it there.\n")

	b.WriteString("\n## Version drift\n\n")
	b.WriteString("Every `use` below promotes a module to a main module, which makes its\n")
	b.WriteString("requirement graph an MVS root. Third-party versions can therefore only\n")
	b.WriteString("move **up** from what the artifact shipped. Run `wgo rig verify` to see\n")
	b.WriteString("whether they have; a rig that quietly builds against a different gRPC\n")
	b.WriteString("than production is worse than no rig at all.\n")

	b.WriteString("\n## Layout\n\n")
	b.WriteString("| Module | Directory | Pin |\n|---|---|---|\n")
	byDir := map[string][]Member{}
	for _, mem := range m.Members {
		byDir[mem.Checkout] = append(byDir[mem.Checkout], mem)
	}
	for _, c := range m.Checkouts {
		mems := byDir[c.Dir]
		sort.Slice(mems, func(i, j int) bool { return mems[i].Path < mems[j].Path })
		for _, mem := range mems {
			fmt.Fprintf(&b, "| `%s` | `%s` | `%s` |\n", mem.Path, mem.UseDir(), pinLabel(c))
		}
	}
	return b.String()
}

// pinLabel describes what a checkout is pinned to, preferring the tag because
// that is what a reader recognises from the release.
func pinLabel(c Checkout) string {
	if c.Tag != "" {
		return c.Tag
	}
	return shortCommit(c.Commit)
}

// contentsLabel summarises how much of the repository a checkout materialises.
func contentsLabel(c Checkout) string {
	if c.Full || len(c.Sparse) == 0 {
		return "full"
	}
	quoted := make([]string, 0, len(c.Sparse))
	for _, s := range c.Sparse {
		quoted = append(quoted, "`"+s+"`")
	}
	return "sparse: " + strings.Join(quoted, ", ")
}

// shellQuote renders s as a single-quoted POSIX shell word.
//
// Rig roots come from user config and can hold spaces; an unquoted path would
// split into two words and export a truncated GOWORK.
func shellQuote(s string) string {
	return "'" + strings.ReplaceAll(s, "'", `'\''`) + "'"
}
