package rig

import (
	"fmt"
	"sort"
	"strings"
)

// RenderGoWork produces the rig's go.work.
//
// It is rendered here rather than assembled with `go work init`/`go work use`
// so the file is deterministic and can carry comments. The comments are the
// point: a rig's go.work is the one file a confused reader will open, and it
// needs to say which commit each checkout came from and which commands would
// destroy the pin.
//
// The output is still handed to `go work edit -fmt` afterwards, which parses
// the file and so doubles as validation.
func RenderGoWork(m *Manifest) string {
	var b strings.Builder

	b.WriteString("// Generated by `wgo rig` — do not edit; `wgo rig sync` rewrites it.\n")
	fmt.Fprintf(&b, "// rig: %s", m.Name)
	if src := sourceSummary(m.Source); src != "" {
		fmt.Fprintf(&b, "  from: %s", src)
	}
	b.WriteString("\n")
	b.WriteString("//\n")
	b.WriteString("// Every `use` below promotes a module to a main module, which makes its\n")
	b.WriteString("// requirement graph an MVS root: third-party versions can only move UP from\n")
	b.WriteString("// what the artifact shipped. Run `wgo rig verify` to see whether they have.\n")
	b.WriteString("//\n")
	b.WriteString("// Do NOT run `go mod tidy` or `go work sync` here: both write the workspace\n")
	b.WriteString("// build list back into the checked-out go.mod files and destroy the pin.\n")

	if m.GoVersion != "" {
		fmt.Fprintf(&b, "\ngo %s\n", m.GoVersion)
	}

	b.WriteString("\nuse (\n")
	for _, line := range useBlock(m) {
		b.WriteString(line)
		b.WriteString("\n")
	}
	b.WriteString(")\n")

	if replaces := frozenReplaces(m); len(replaces) > 0 {
		b.WriteString("\n// Frozen by `wgo rig verify --freeze`: these were pulled above the versions\n")
		b.WriteString("// the artifact shipped with, and are pinned back down. `wgo rig verify\n")
		b.WriteString("// --unfreeze <module>` removes one.\n")
		b.WriteString("replace (\n")
		for _, r := range replaces {
			fmt.Fprintf(&b, "\t%s => %s %s\n", r.path, r.path, r.version)
		}
		b.WriteString(")\n")
	}

	return b.String()
}

// useBlock renders the use entries, grouped by checkout with a header naming
// the commit each group came from.
func useBlock(m *Manifest) []string {
	byCheckout := map[string][]Member{}
	for _, mem := range m.Members {
		byCheckout[mem.Checkout] = append(byCheckout[mem.Checkout], mem)
	}

	var lines []string
	for _, c := range m.Checkouts {
		mems := byCheckout[c.Dir]
		if len(mems) == 0 {
			continue
		}
		sort.Slice(mems, func(i, j int) bool { return mems[i].UseDir() < mems[j].UseDir() })

		anchor := c.Tag
		if anchor == "" {
			anchor = shortCommit(c.Commit)
		}
		header := fmt.Sprintf("\t// %s @ %s", c.Repo, anchor)
		if c.Tag != "" && c.Commit != "" {
			header += fmt.Sprintf(" (%s)", shortCommit(c.Commit))
		}
		if c.Full {
			header += " [full]"
		}
		lines = append(lines, header)

		for _, mem := range mems {
			line := "\t" + mem.UseDir()
			if mem.Indirect {
				// One space, not two: `go work edit -fmt` runs over this file
				// after it is written and would collapse a wider gap, leaving
				// the file on disk differing from what we rendered.
				line += " // indirect"
			}
			lines = append(lines, line)
		}
	}
	return lines
}

type frozenReplace struct{ path, version string }

// frozenReplaces resolves each frozen module against the stored baseline. A
// frozen module with no baseline version cannot be pinned and is dropped: an
// empty version would render a syntactically invalid replace.
func frozenReplaces(m *Manifest) []frozenReplace {
	var out []frozenReplace
	for _, p := range m.Frozen {
		if v := m.Baseline[p]; v != "" {
			out = append(out, frozenReplace{path: p, version: v})
		}
	}
	sort.Slice(out, func(i, j int) bool { return out[i].path < out[j].path })
	return out
}

func sourceSummary(s Source) string {
	switch s.Kind {
	case "repo":
		return s.Ref
	case "binary":
		return s.Binary
	case "manual":
		if len(s.Modules) == 0 {
			return "explicit modules"
		}
		return strings.Join(s.Modules, ", ")
	}
	return ""
}
