package rig

import (
	"os"
	"path/filepath"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

// sampleManifest exercises every field, including the ones only a later command
// writes, so the round-trip test proves nothing is silently dropped.
func sampleManifest() *Manifest {
	return &Manifest{
		Name:       "dsp-2.7.1",
		Created:    "2026-08-25T00:00:00Z",
		WgoVersion: "0.1.0",
		GoVersion:  "1.24.5",
		Sparse:     true,
		Source: Source{
			Kind:        "repo",
			Ref:         "virtru-corp/data-security-platform@v2.7.1",
			OrgPrefixes: []string{"github.com/opentdf", "github.com/virtru-corp"},
		},
		Primary:    "github.com/virtru-corp/data-security-platform/v2",
		PrimaryUse: []string{"", "sdk"},
		Checkouts: []Checkout{
			{
				Dir:       "data-security-platform-v2.7.1",
				Workspace: "rig-dsp-2.7.1-data-security-platform-v2.7.1",
				Repo:      "virtru-corp/data-security-platform",
				MainClone: dspClone,
				Revset:    `present(tags(exact:"v2.7.1"))`,
				Commit:    "dsp0000000000000000000000000000000000000",
				Tag:       "v2.7.1",
				Full:      true,
			},
			{
				Dir:       "platform-service-v0.11.6",
				Workspace: "rig-dsp-2.7.1-platform-service-v0.11.6",
				Repo:      "opentdf/platform",
				MainClone: platformClone,
				Revset:    `present(tags(exact:"service/v0.11.6"))`,
				Commit:    "6a5827d7000000000000000000000000000000aa",
				Tag:       "service/v0.11.6",
				Sparse:    []string{"service"},
			},
		},
		Members: []Member{
			{
				Path:     "github.com/virtru-corp/data-security-platform/v2",
				Version:  "v2.7.1",
				Checkout: "data-security-platform-v2.7.1",
			},
			{
				Path:     "github.com/opentdf/platform/service",
				Version:  "v0.11.6",
				Checkout: "platform-service-v0.11.6",
				Subdir:   "service",
				Indirect: true,
			},
		},
		Skipped: []Skip{
			{Path: "github.com/opentdf/private", Version: "v0.1.0", Reason: "unreachable: no such repo"},
		},
		Baseline: map[string]string{
			"google.golang.org/grpc": "v1.65.0",
			"golang.org/x/net":       "v0.27.0",
		},
		Frozen: []string{"golang.org/x/net"},
	}
}

func TestSaveLoadRoundTrip(t *testing.T) {
	root := t.TempDir()
	want := sampleManifest()
	require.NoError(t, Save(root, want))

	got, err := Load(root)
	require.NoError(t, err)
	assert.Equal(t, want, got)
}

// Save creates the rig root: `wgo rig new` writes the manifest before it has
// materialised anything else into the directory.
func TestSaveCreatesRoot(t *testing.T) {
	root := filepath.Join(t.TempDir(), "nested", "dsp-2.7.1")
	require.NoError(t, Save(root, sampleManifest()))

	_, err := os.Stat(ManifestPath(root))
	require.NoError(t, err)
}

// The manifest is meant to be read by a human trying to work out what a
// directory full of checkouts is, so it leads with an explanation.
func TestSaveWritesHeaderComment(t *testing.T) {
	root := t.TempDir()
	require.NoError(t, Save(root, sampleManifest()))

	data, err := os.ReadFile(ManifestPath(root))
	require.NoError(t, err)
	assert.Contains(t, string(data), "# Generated by `wgo rig`")
}

// A partially written rig.toml would leave `wgo rig rm` unable to find the
// workspaces it has to forget, so the previous manifest must survive a failed
// write. Approximated here by checking no temp file is left behind.
func TestSaveLeavesNoTempFiles(t *testing.T) {
	root := t.TempDir()
	require.NoError(t, Save(root, sampleManifest()))
	require.NoError(t, Save(root, sampleManifest()))

	entries, err := os.ReadDir(root)
	require.NoError(t, err)
	var names []string
	for _, e := range entries {
		names = append(names, e.Name())
	}
	assert.Equal(t, []string{ManifestName}, names)
}

func TestSaveRejectsInvalidManifest(t *testing.T) {
	root := t.TempDir()
	m := sampleManifest()
	m.Name = ""

	require.Error(t, Save(root, m))
	_, err := os.Stat(ManifestPath(root))
	assert.True(t, os.IsNotExist(err), "an invalid manifest must not be written")
}

func TestLoadMissingManifest(t *testing.T) {
	_, err := Load(t.TempDir())
	assert.ErrorIs(t, err, ErrNoManifest)
}

func TestLoadMalformedManifest(t *testing.T) {
	root := t.TempDir()
	require.NoError(t, os.WriteFile(ManifestPath(root), []byte("name = \n"), 0o644))

	_, err := Load(root)
	require.Error(t, err)
	assert.NotErrorIs(t, err, ErrNoManifest, "a corrupt manifest is not a missing one")
}

func TestValidate(t *testing.T) {
	tests := []struct {
		name    string
		mutate  func(*Manifest)
		wantErr string
	}{
		{"valid", func(*Manifest) {}, ""},
		{"no name", func(m *Manifest) { m.Name = "  " }, "no name"},
		{"checkout without dir", func(m *Manifest) { m.Checkouts[0].Dir = "" }, "has no dir"},
		{"checkout without workspace", func(m *Manifest) { m.Checkouts[0].Workspace = "" }, "no workspace name"},
		{"checkout without main clone", func(m *Manifest) { m.Checkouts[0].MainClone = "" }, "no main clone"},
		{
			"duplicate checkout dir",
			func(m *Manifest) { m.Checkouts[1].Dir = m.Checkouts[0].Dir },
			"duplicate checkout dir",
		},
		{"member without path", func(m *Manifest) { m.Members[0].Path = "" }, "no module path"},
		{
			"member referencing unknown checkout",
			func(m *Manifest) { m.Members[0].Checkout = "nope" },
			"unknown checkout",
		},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			m := sampleManifest()
			tt.mutate(m)
			err := m.Validate()
			if tt.wantErr == "" {
				assert.NoError(t, err)
				return
			}
			require.Error(t, err)
			assert.Contains(t, err.Error(), tt.wantErr)
		})
	}
}

func TestCheckoutByDir(t *testing.T) {
	m := sampleManifest()

	c, ok := m.CheckoutByDir("platform-service-v0.11.6")
	require.True(t, ok)
	assert.Equal(t, "opentdf/platform", c.Repo)

	_, ok = m.CheckoutByDir("nope")
	assert.False(t, ok)
}

func TestMemberUseDir(t *testing.T) {
	tests := []struct {
		name   string
		member Member
		want   string
	}{
		{"root module", Member{Checkout: "otdfctl-v0.26.2"}, "./src/otdfctl-v0.26.2"},
		{
			"nested module",
			Member{Checkout: "platform-service-v0.11.6", Subdir: "service"},
			"./src/platform-service-v0.11.6/service",
		},
		{
			"deeply nested module",
			Member{Checkout: "platform-protocol-go-v0.13.0", Subdir: "protocol/go"},
			"./src/platform-protocol-go-v0.13.0/protocol/go",
		},
	}
	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			assert.Equal(t, tt.want, tt.member.UseDir())
		})
	}
}

func TestManifestRoot(t *testing.T) {
	m := &Manifest{Name: "dsp-2.7.1"}
	assert.Equal(t, filepath.Join("/rigs", "dsp-2.7.1"), m.Root("/rigs"))
}

func TestList(t *testing.T) {
	rigDir := t.TempDir()

	for _, name := range []string{"dsp-2.7.1", "abc-1.0.0"} {
		m := sampleManifest()
		m.Name = name
		require.NoError(t, Save(filepath.Join(rigDir, name), m))
	}
	// rig.dir belongs to the user and may hold anything: a directory without a
	// manifest, and a plain file, are both skipped rather than reported.
	require.NoError(t, os.MkdirAll(filepath.Join(rigDir, "not-a-rig"), 0o755))
	require.NoError(t, os.WriteFile(filepath.Join(rigDir, "notes.md"), []byte("hi"), 0o644))

	got, err := List(rigDir)
	require.NoError(t, err)
	require.Len(t, got, 2)
	assert.Equal(t, "abc-1.0.0", got[0].Name, "rigs are sorted by name")
	assert.Equal(t, "dsp-2.7.1", got[1].Name)
}

// `wgo rig ls` before the first rig exists must print an empty list, not an
// error about a directory wgo has never had a reason to create.
func TestListMissingDir(t *testing.T) {
	got, err := List(filepath.Join(t.TempDir(), "nope"))
	require.NoError(t, err)
	assert.Empty(t, got)
}
