package cmd

import (
	"bytes"
	"errors"
	"fmt"
	"io/fs"
	"os"
	"path/filepath"
	"slices"
	"sort"

	"github.com/virtru/wgo/internal/claudemd"
	"github.com/virtru/wgo/internal/discovery"
	specpkg "github.com/virtru/wgo/internal/spec"
)

// sharedClaudeMD describes the CLAUDE.md to generate at a multi-repo
// workspace root.
type sharedClaudeMD struct {
	Root        string // shared workspace root; the file lands at Root/CLAUDE.md
	Ticket      string // "" when the branch carries no ticket
	Description string // goal text used when no spec file is found
	SpecRepoDir string // repo dir known to hold the spec; "" to search every repo
	Repos       []claudemd.RepoEntry
}

// writeSharedClaudeMD renders and writes <Root>/CLAUDE.md, onboarding a coding
// agent to the repos in a multi-repo wgo workspace.
//
// It is a no-op with fewer than 2 repos: the file exists to orient an agent
// *across* repos, which is vacuous for one.
//
// The file is generated scaffolding and is rewritten on every run so the repo
// list stays accurate as `wgo join` adds repos. To keep that safe it only
// overwrites a file it recognizes as its own (claudemd.Marker) — a CLAUDE.md
// without the marker is assumed hand-written and is left alone with a warning.
// Both callers treat a returned error as non-fatal.
func writeSharedClaudeMD(req sharedClaudeMD) error {
	if len(req.Repos) < 2 {
		return nil
	}

	sorted := slices.Clone(req.Repos)
	sort.Slice(sorted, func(i, j int) bool { return sorted[i].Dir < sorted[j].Dir })

	data, err := claudemd.RenderTemplate(claudemd.TemplateData{
		Ticket:      req.Ticket,
		Description: req.Description,
		SpecPath:    resolveSpecPath(req.Root, req.Ticket, req.SpecRepoDir, sorted),
		Repos:       sorted,
	})
	if err != nil {
		return fmt.Errorf("render shared CLAUDE.md: %w", err)
	}

	path := filepath.Join(req.Root, "CLAUDE.md")
	existing, readErr := os.ReadFile(path)
	switch {
	case readErr == nil && !bytes.HasPrefix(existing, []byte(claudemd.Marker)):
		fmt.Fprintf(os.Stderr, "warning: %s already exists and was not generated by wgo; leaving it unchanged\n", path)
		return nil
	case readErr != nil && !errors.Is(readErr, fs.ErrNotExist):
		return fmt.Errorf("read %s: %w", path, readErr)
	}
	regenerating := readErr == nil

	if err := os.WriteFile(path, data, 0o644); err != nil {
		return fmt.Errorf("write %s: %w", path, err)
	}
	verb := "wrote"
	if regenerating {
		verb = "regenerated"
	}
	fmt.Fprintf(os.Stderr, "%s shared CLAUDE.md (%d repos): %s\n", verb, len(sorted), path)
	return nil
}

// resolveSpecPath finds the spec for ticket among repos and returns its path
// relative to root, or "" when there is no ticket or no spec anywhere.
func resolveSpecPath(root, ticket, specRepoDir string, repos []claudemd.RepoEntry) string {
	if ticket == "" {
		return ""
	}
	for _, r := range specSearchOrder(repos, specRepoDir) {
		rel, err := findSpecRel(root, r.Dir, ticket)
		if err == nil {
			return rel
		}
		// A missing spec/ dir or spec file is the normal case; anything else
		// (unreadable dir, spec/ is a file) is worth surfacing, but keep
		// scanning so one broken repo can't hide a sibling's spec.
		if !errors.Is(err, fs.ErrNotExist) {
			fmt.Fprintf(os.Stderr, "warning: could not check for spec in %s: %v\n", r.Dir, err)
		}
	}
	return ""
}

// mergeRepoLabels unions the repos found on disk with the ones this `wgo add`
// run was asked for. Discovery keeps repos that an earlier `wgo join` added, so
// re-running `add` with a narrower -r list doesn't drop them; the -r specs
// supply exact owner/repo labels and cover any repo discovery missed.
func mergeRepoLabels(discovered []claudemd.RepoEntry, specs []repoSpec) []claudemd.RepoEntry {
	labels := make(map[string]string, len(discovered)+len(specs))
	for _, r := range discovered {
		labels[r.Dir] = r.Label
	}
	for _, sp := range specs {
		labels[sp.repo] = sp.String()
	}
	merged := make([]claudemd.RepoEntry, 0, len(labels))
	for dir, label := range labels {
		merged = append(merged, claudemd.RepoEntry{Dir: dir, Label: label})
	}
	return merged
}

// isManagedWorkspaceRoot reports whether root is a direct child of
// worktreesDir — the layout `wgo add` creates and `wgo join` extends. `join`
// infers its root from the cwd rather than being told, so this is the guard
// that keeps generated files inside wgo's own tree instead of in whatever
// directory happened to be one level up.
func isManagedWorkspaceRoot(worktreesDir, root string) bool {
	wd, r := absResolved(worktreesDir), absResolved(root)
	return wd != "" && r != "" && filepath.Dir(r) == wd
}

// absResolved returns p as an absolute, symlink-resolved path, falling back to
// the unresolved absolute form when p doesn't exist yet. Returns "" if p is
// empty or can't be made absolute.
func absResolved(p string) string {
	if p == "" {
		return ""
	}
	abs, err := filepath.Abs(p)
	if err != nil {
		return ""
	}
	if resolved, err := filepath.EvalSymlinks(abs); err == nil {
		return resolved
	}
	return abs
}

// specSearchOrder returns repos with first moved to the front, so `add` links
// the spec it just wrote rather than an identically-named one in a repo that
// happens to sort earlier. A first of "" — or one already leading, or absent
// from repos — is a no-op.
func specSearchOrder(repos []claudemd.RepoEntry, first string) []claudemd.RepoEntry {
	i := slices.IndexFunc(repos, func(r claudemd.RepoEntry) bool { return r.Dir == first })
	if i <= 0 {
		return repos
	}
	out := slices.Clone(repos)
	copy(out[1:], out[:i])
	out[0] = repos[i]
	return out
}

// findSpecRel locates the spec for ticket in <root>/<dir> and returns its path
// relative to root, slash-separated for use in a markdown link. The on-disk
// filename comes back verbatim from spec.FindByTicket, which is what keeps the
// link resolving on case-sensitive filesystems and on github.com.
func findSpecRel(root, dir, ticket string) (string, error) {
	abs, err := specpkg.FindByTicket(filepath.Join(root, dir), ticket)
	if err != nil {
		return "", err
	}
	return filepath.ToSlash(filepath.Join(dir, "spec", filepath.Base(abs))), nil
}

// repoDiscoveryClient is the narrow jj surface discoverSharedRepos needs.
// jj.Client satisfies it; kept small so tests can fake it easily.
type repoDiscoveryClient interface {
	RemoteURLs(path string) (map[string]string, error)
}

// discoverSharedRepos scans sharedRoot's immediate subdirectories for repo
// roots and labels each from its remotes. Unlike `add`, which already has the
// repo list in memory, `join` reconstructs it from the filesystem so repos
// added by earlier runs survive regeneration.
//
// A subdirectory counts as a repo only if it directly contains .jj/, which is
// what discovery.IsRepo checks. jj.Client.IsRepo answers a different question —
// it walks ancestors, so "is this inside a repo" — and would report true for
// every subdirectory whenever sharedRoot is itself inside a repo.
func discoverSharedRepos(jjc repoDiscoveryClient, sharedRoot string) ([]claudemd.RepoEntry, error) {
	entries, err := os.ReadDir(sharedRoot)
	if err != nil {
		return nil, err
	}

	var repos []claudemd.RepoEntry
	for _, e := range entries {
		repoPath := filepath.Join(sharedRoot, e.Name())
		if !discovery.IsRepo(repoPath) {
			continue
		}
		repos = append(repos, claudemd.RepoEntry{
			Dir:   e.Name(),
			Label: repoLabel(jjc, repoPath, e.Name()),
		})
	}
	return repos, nil
}

// repoLabel names repoPath as "owner/repo", falling back to dir when no remote
// resolves. The fallback warns: a label that quietly degrades to a bare
// directory name, in a file whose job is to orient an agent, is worth a line of
// output.
func repoLabel(jjc repoDiscoveryClient, repoPath, dir string) string {
	ownerRepo, err := ownerRepoFor(jjc, repoPath)
	if err != nil {
		fmt.Fprintf(os.Stderr, "warning: %v; using directory name %q\n", err, dir)
		return dir
	}
	return ownerRepo
}
