package cmd

import (
	"bytes"
	"errors"
	"fmt"
	"io/fs"
	"os"
	"path/filepath"
	"sort"
	"strings"

	"github.com/virtru/wgo/internal/claudemd"
)

// sharedClaudeMD describes the CLAUDE.md to generate at a multi-repo
// workspace root.
type sharedClaudeMD struct {
	Root        string // shared workspace root; the file lands at Root/CLAUDE.md
	Ticket      string // "" when the branch carries no ticket
	Description string // goal text used when no spec file is found
	SpecRepoDir string // repo dir known to hold the spec; "" to search every repo
	Repos       []claudemd.RepoEntry
}

// writeSharedClaudeMD renders and writes <Root>/CLAUDE.md, onboarding a coding
// agent to the repos in a multi-repo wgo workspace.
//
// It is a no-op with fewer than 2 repos: the file exists to orient an agent
// *across* repos, which is vacuous for one.
//
// The file is generated scaffolding and is rewritten on every run so the repo
// list stays accurate as `wgo join` adds repos. To keep that safe it only
// overwrites a file it recognizes as its own (claudemd.Marker) — a CLAUDE.md
// without the marker is assumed hand-written and is left alone with a warning.
// Both callers treat a returned error as non-fatal.
func writeSharedClaudeMD(req sharedClaudeMD) error {
	if len(req.Repos) < 2 {
		return nil
	}

	sorted := append([]claudemd.RepoEntry(nil), req.Repos...)
	sort.Slice(sorted, func(i, j int) bool { return sorted[i].Dir < sorted[j].Dir })

	specPath := ""
	if req.Ticket != "" {
		for _, r := range specSearchOrder(sorted, req.SpecRepoDir) {
			rel, err := findSpecRel(req.Root, r.Dir, req.Ticket)
			if err == nil {
				specPath = rel
				break
			}
			// A missing spec/ dir or spec file is the normal case; anything
			// else (unreadable dir, spec/ is a file) is worth surfacing, but
			// keep scanning so one broken repo can't hide a sibling's spec.
			if !errors.Is(err, fs.ErrNotExist) {
				fmt.Fprintf(os.Stderr, "warning: could not check for spec in %s: %v\n", r.Dir, err)
			}
		}
	}

	data, err := claudemd.RenderTemplate(claudemd.TemplateData{
		Ticket:      req.Ticket,
		Description: req.Description,
		SpecPath:    specPath,
		Repos:       sorted,
	})
	if err != nil {
		return fmt.Errorf("render shared CLAUDE.md: %w", err)
	}

	path := filepath.Join(req.Root, "CLAUDE.md")
	existing, readErr := os.ReadFile(path)
	switch {
	case readErr == nil && !bytes.HasPrefix(existing, []byte(claudemd.Marker)):
		fmt.Fprintf(os.Stderr, "warning: %s already exists and was not generated by wgo; leaving it unchanged\n", path)
		return nil
	case readErr != nil && !errors.Is(readErr, fs.ErrNotExist):
		return fmt.Errorf("read %s: %w", path, readErr)
	}

	if err := os.WriteFile(path, data, 0o644); err != nil {
		return fmt.Errorf("write %s: %w", path, err)
	}
	verb := "wrote"
	if readErr == nil {
		verb = "regenerated"
	}
	fmt.Fprintf(os.Stderr, "%s shared CLAUDE.md (%d repos): %s\n", verb, len(sorted), path)
	return nil
}

// isManagedWorkspaceRoot reports whether root is a direct child of
// worktreesDir — the layout `wgo add` creates and `wgo join` extends. `join`
// infers its root from the cwd rather than being told, so this is the guard
// that keeps generated files inside wgo's own tree instead of in whatever
// directory happened to be one level up.
func isManagedWorkspaceRoot(worktreesDir, root string) bool {
	wd, r := absResolved(worktreesDir), absResolved(root)
	return wd != "" && r != "" && filepath.Dir(r) == wd
}

// absResolved returns p as an absolute, symlink-resolved path, falling back to
// the unresolved absolute form when p doesn't exist yet. Returns "" if p is
// empty or can't be made absolute.
func absResolved(p string) string {
	if p == "" {
		return ""
	}
	abs, err := filepath.Abs(p)
	if err != nil {
		return ""
	}
	if resolved, err := filepath.EvalSymlinks(abs); err == nil {
		return resolved
	}
	return abs
}

// specSearchOrder returns repos with first at the front, so `add` links the
// spec it just wrote rather than an identically-named one in a repo that
// happens to sort earlier. A first of "" (or one not in repos) is a no-op.
func specSearchOrder(repos []claudemd.RepoEntry, first string) []claudemd.RepoEntry {
	if first == "" {
		return repos
	}
	out := make([]claudemd.RepoEntry, 0, len(repos))
	for _, r := range repos {
		if r.Dir == first {
			out = append(out, r)
		}
	}
	for _, r := range repos {
		if r.Dir != first {
			out = append(out, r)
		}
	}
	return out
}

// findSpecRel locates <root>/<dir>/spec/<ticket>.md and returns its path
// relative to root, slash-separated.
//
// Matching is case-insensitive because tickets reach us uppercased (see
// spec.ParseTicketFromBranch) while specs for GitHub issues are conventionally
// lowercase on disk — spec/gh-9.md. The returned path uses the real on-disk
// filename rather than the ticket, so the link resolves on case-sensitive
// filesystems and on github.com even when the stat that found it succeeded
// only because the local filesystem is case-insensitive.
func findSpecRel(root, dir, ticket string) (string, error) {
	entries, err := os.ReadDir(filepath.Join(root, dir, "spec"))
	if err != nil {
		return "", err
	}
	want := ticket + ".md"
	for _, e := range entries {
		if !e.IsDir() && strings.EqualFold(e.Name(), want) {
			return filepath.ToSlash(filepath.Join(dir, "spec", e.Name())), nil
		}
	}
	return "", fs.ErrNotExist
}

// repoDiscoveryClient is the narrow jj surface discoverSharedRepos needs.
// jj.Client satisfies it; kept small so tests can fake it easily.
type repoDiscoveryClient interface {
	RemoteURLs(path string) (map[string]string, error)
}

// discoverSharedRepos scans sharedRoot's immediate subdirectories for repo
// roots and labels each from its remotes. Unlike `add`, which already has the
// repo list in memory, `join` reconstructs it from the filesystem so repos
// added by earlier runs survive regeneration.
//
// A subdirectory counts as a repo root only if it directly contains .jj/.
// jj.Client.IsRepo is deliberately not used: it walks ancestors looking for
// .jj/, so it answers "is this inside a repo" and would report true for every
// subdirectory whenever sharedRoot is itself inside a repo.
func discoverSharedRepos(jjc repoDiscoveryClient, sharedRoot string) ([]claudemd.RepoEntry, error) {
	entries, err := os.ReadDir(sharedRoot)
	if err != nil {
		return nil, err
	}

	var repos []claudemd.RepoEntry
	for _, e := range entries {
		// Stat rather than e.IsDir() so a symlinked repo checkout counts.
		repoPath := filepath.Join(sharedRoot, e.Name())
		if info, err := os.Stat(repoPath); err != nil || !info.IsDir() {
			continue
		}
		if info, err := os.Stat(filepath.Join(repoPath, ".jj")); err != nil || !info.IsDir() {
			continue
		}
		repos = append(repos, claudemd.RepoEntry{
			Dir:   e.Name(),
			Label: repoLabel(jjc, repoPath, e.Name()),
		})
	}
	return repos, nil
}

// repoLabel resolves repoPath to "owner/repo", preferring "origin" and then
// trying every other remote in name order before giving up and using dir.
// Each fallback warns: a label that quietly degrades to a bare directory name,
// in a file whose job is to orient an agent, is worth a line of output.
func repoLabel(jjc repoDiscoveryClient, repoPath, dir string) string {
	remotes, err := jjc.RemoteURLs(repoPath)
	if err != nil {
		fmt.Fprintf(os.Stderr, "warning: could not read remotes for %s, using directory name: %v\n", repoPath, err)
		return dir
	}
	if label := extractOwnerRepo(remotes["origin"]); label != "" {
		return label
	}

	names := make([]string, 0, len(remotes))
	for name := range remotes {
		if name != "origin" {
			names = append(names, name)
		}
	}
	sort.Strings(names)
	for _, name := range names {
		if label := extractOwnerRepo(remotes[name]); label != "" {
			return label
		}
	}

	fmt.Fprintf(os.Stderr, "warning: no remote for %s resolves to owner/repo, using directory name\n", repoPath)
	return dir
}
