package sync

import (
	"encoding/json"
	"errors"
	"fmt"
	"regexp"
	"sort"
	"strings"
)

// ErrMalformedMarkerData reports that a marker block was present but its
// machine-readable sidecar could not be parsed. Callers that want the
// spec's "treat malformed as absent and rebuild" behavior should handle
// this with errors.Is(err, ErrMalformedMarkerData) and continue.
var ErrMalformedMarkerData = errors.New("stack: malformed marker data")

// MarkerData is the machine-parseable topology embedded in each PR-body
// marker block. The spec requires that the block be sufficient for another
// machine to rebuild local state by reading GitHub, so we render it next to
// the human-readable list inside an HTML comment (invisible in GitHub's
// rendered markdown) and expose ParseNodes to read it back.
//
// Cross-repo stacks are out of scope; branches are scoped to the same repo
// the consumer is running wgo in, so we omit any local-filesystem paths and
// use branch names as the stable identifiers within the stack.
type MarkerData struct {
	StackID string           `json:"stack_id"`
	Nodes   []MarkerDataNode `json:"nodes"`
}

// MarkerDataNode is a single stack node in the wire format. Parents are the
// branch names (not annotation keys) of in-stack parents; external parents
// are omitted because the consumer can't translate them.
type MarkerDataNode struct {
	Branch   string   `json:"branch"`
	PRNumber int      `json:"pr,omitempty"`
	Parents  []string `json:"parents,omitempty"`
}

// MarkerNode is the per-PR data rendered into the marker block.
// Repo is informational only — the marker uses PR numbers as identity.
type MarkerNode struct {
	Key      string // store annotation key ("repo:branch") — used for self-recognition
	Branch   string
	PRNumber int      // 0 when no PR has been opened yet
	Parents  []string // annotation keys of in-stack parents
}

// Marker captures everything `Render` needs to draw the block.
// The block lists members in TopoSort order, marks one as `Self`,
// and links PR numbers when present.
type Marker struct {
	StackID string
	Self    string       // annotation key of the PR whose body this is
	Nodes   []MarkerNode // ordered (typically topologically)
}

const (
	markerOpenPrefix = "<!-- wgo-stack:"
	markerOpenSuffix = " -->"
	markerClose      = "<!-- /wgo-stack -->"
	markerDataPrefix = "<!-- wgo-stack-data:"
	markerDataSuffix = " -->"
)

// markerBlockPattern matches the entire fenced block, including the
// open and close markers, allowing for any stack id between them.
var markerBlockPattern = regexp.MustCompile(
	`(?s)<!-- wgo-stack:[^ ]+ -->.*?<!-- /wgo-stack -->`,
)

// markerDataPattern matches the JSON-bearing sidecar comment inside a block.
// Non-greedy so multiple blocks in one body don't collapse into one match.
var markerDataPattern = regexp.MustCompile(
	`(?s)<!-- wgo-stack-data:(.+?) -->`,
)

// Render produces the markdown block to embed in a PR body.
// Output is stable across calls with equivalent input so PR bodies don't
// get spurious diffs when wgo syncs.
func (m Marker) Render() string {
	var b strings.Builder
	fmt.Fprintf(&b, "%s%s%s\n", markerOpenPrefix, m.StackID, markerOpenSuffix)
	fmt.Fprintf(&b, "**Stack** (`%s`):\n\n", m.StackID)

	if len(m.Nodes) == 0 {
		b.WriteString("_no members_\n")
	} else {
		// Map keys -> PR numbers for parent links.
		prByKey := make(map[string]int, len(m.Nodes))
		branchByKey := make(map[string]string, len(m.Nodes))
		for _, n := range m.Nodes {
			prByKey[n.Key] = n.PRNumber
			branchByKey[n.Key] = n.Branch
		}

		for _, n := range m.Nodes {
			isSelf := n.Key == m.Self
			line := renderNodeLine(n, prByKey, branchByKey)
			if isSelf {
				fmt.Fprintf(&b, "- **%s** ← this PR\n", line)
			} else {
				fmt.Fprintf(&b, "- %s\n", line)
			}
		}
	}

	// Embed the machine-parseable topology so another machine can rebuild
	// local state by reading GitHub. Goes BEFORE the human-readable trailer
	// so cosmetic edits to the trailer line don't risk corrupting the data.
	if data, err := json.Marshal(m.Data()); err == nil {
		fmt.Fprintf(&b, "\n%s%s%s\n", markerDataPrefix, string(data), markerDataSuffix)
	}

	b.WriteString("\n_Generated by [`wgo stack`](" + docsURL + "). Edit text above or below this block, not inside it._\n")
	b.WriteString(markerClose)
	return b.String()
}

// Data converts the (display-oriented) Marker into the (wire-format)
// MarkerData embedded in the PR body. External parents — those whose key
// doesn't resolve to an in-stack node — are dropped, since a remote
// consumer has no way to interpret them.
func (m Marker) Data() MarkerData {
	branchByKey := make(map[string]string, len(m.Nodes))
	for _, n := range m.Nodes {
		branchByKey[n.Key] = n.Branch
	}
	data := MarkerData{StackID: m.StackID}
	for _, n := range m.Nodes {
		node := MarkerDataNode{Branch: n.Branch, PRNumber: n.PRNumber}
		for _, pk := range n.Parents {
			if pBranch, ok := branchByKey[pk]; ok {
				node.Parents = append(node.Parents, pBranch)
			}
		}
		data.Nodes = append(data.Nodes, node)
	}
	return data
}

// ParseNodes extracts the MarkerData sidecar from a PR body. Returns
// (nil, nil) when no sidecar is present, so callers can distinguish
// "no marker" from "malformed marker".
//
// When a marker block exists but its JSON cannot be parsed, returns
// ErrMalformedMarkerData wrapped with the parse details. Callers that
// want the spec's "treat malformed as absent and rebuild" behavior
// should check errors.Is(err, ErrMalformedMarkerData) and continue:
//
//	data, err := ParseNodes(body)
//	if err != nil {
//	    if errors.Is(err, ErrMalformedMarkerData) {
//	        fmt.Fprintf(os.Stderr, "warning: PR has malformed stack marker, will rebuild: %v\n", err)
//	        data = nil // treat as absent
//	    } else {
//	        return err
//	    }
//	}
func ParseNodes(body string) (*MarkerData, error) {
	match := markerDataPattern.FindStringSubmatch(body)
	if match == nil {
		return nil, nil
	}
	var data MarkerData
	if err := json.Unmarshal([]byte(strings.TrimSpace(match[1])), &data); err != nil {
		return nil, fmt.Errorf("%w: %v", ErrMalformedMarkerData, err)
	}
	return &data, nil
}

// docsURL points at the README section users land on when they click the
// "wgo stack" link in a marker block. Hardcoded to the canonical repo on
// main so the URL is stable even after the PR stack that introduces stacks
// lands and the integration branches are deleted.
const docsURL = "https://github.com/dmihalcik-virtru/wgo#stacked-pull-requests"

func renderNodeLine(n MarkerNode, prByKey map[string]int, branchByKey map[string]string) string {
	var sb strings.Builder
	if n.PRNumber > 0 {
		fmt.Fprintf(&sb, "#%d %s", n.PRNumber, n.Branch)
	} else {
		fmt.Fprintf(&sb, "%s _(no PR)_", n.Branch)
	}

	// Stable parent display: only in-stack parents (those we know branches for),
	// sorted by branch name for determinism.
	var parentLabels []string
	for _, pk := range n.Parents {
		branch, known := branchByKey[pk]
		if !known {
			continue
		}
		if num, ok := prByKey[pk]; ok && num > 0 {
			parentLabels = append(parentLabels, fmt.Sprintf("#%d", num))
		} else {
			parentLabels = append(parentLabels, branch)
		}
	}
	sort.Strings(parentLabels)
	switch len(parentLabels) {
	case 0:
		sb.WriteString(" ← root")
	case 1:
		fmt.Fprintf(&sb, " ↳ on %s", parentLabels[0])
	default:
		fmt.Fprintf(&sb, " ↳ on %s", strings.Join(parentLabels, " + "))
	}
	return sb.String()
}

// ApplyMarker inserts (or replaces) the marker block in `body`. If the body
// has no existing marker, the new block is appended with a blank-line
// separator. Returns the updated body.
func ApplyMarker(body, rendered string) string {
	if markerBlockPattern.MatchString(body) {
		return markerBlockPattern.ReplaceAllString(body, regexReplaceLiteral(rendered))
	}
	body = strings.TrimRight(body, "\n")
	if body == "" {
		return rendered + "\n"
	}
	return body + "\n\n" + rendered + "\n"
}

// StripMarker removes any wgo-stack block from the body, leaving surrounding
// text intact. Used when removing a branch from a stack.
func StripMarker(body string) string {
	stripped := markerBlockPattern.ReplaceAllString(body, "")
	// Collapse the blank-line pair we likely left behind.
	stripped = regexp.MustCompile(`\n{3,}`).ReplaceAllString(stripped, "\n\n")
	return strings.TrimRight(stripped, "\n") + "\n"
}

// ExtractStackID returns the stack id from any marker block in `body`,
// or "" if no well-formed block is present.
func ExtractStackID(body string) string {
	block := markerBlockPattern.FindString(body)
	if block == "" {
		return ""
	}
	// "<!-- wgo-stack:ID -->"
	_, rest, ok := strings.Cut(block, markerOpenPrefix)
	if !ok {
		return ""
	}
	id, _, ok := strings.Cut(rest, markerOpenSuffix)
	if !ok {
		return ""
	}
	return strings.TrimSpace(id)
}

// regexReplaceLiteral escapes `$` so the replacement is treated literally
// by regexp.ReplaceAllString.
func regexReplaceLiteral(s string) string {
	return strings.ReplaceAll(s, "$", "$$")
}
