package stack

import (
	"fmt"
	"regexp"
	"sort"
	"strings"
)

// MarkerNode is the per-PR data rendered into the marker block.
// Repo is informational only — the marker uses PR numbers as identity.
type MarkerNode struct {
	Key      string // store annotation key ("repo:branch") — used for self-recognition
	Branch   string
	PRNumber int      // 0 when no PR has been opened yet
	Parents  []string // annotation keys of in-stack parents
}

// Marker captures everything `Render` needs to draw the block.
// The block lists members in TopoSort order, marks one as `Self`,
// and links PR numbers when present.
type Marker struct {
	StackID string
	Self    string       // annotation key of the PR whose body this is
	Nodes   []MarkerNode // ordered (typically topologically)
}

const (
	markerOpenPrefix = "<!-- wgo-stack:"
	markerOpenSuffix = " -->"
	markerClose      = "<!-- /wgo-stack -->"
)

// markerBlockPattern matches the entire fenced block, including the
// open and close markers, allowing for any stack id between them.
var markerBlockPattern = regexp.MustCompile(
	`(?s)<!-- wgo-stack:[^ ]+ -->.*?<!-- /wgo-stack -->`,
)

// Render produces the markdown block to embed in a PR body.
// Output is stable across calls with equivalent input so PR bodies don't
// get spurious diffs when wgo syncs.
func (m Marker) Render() string {
	var b strings.Builder
	fmt.Fprintf(&b, "%s%s%s\n", markerOpenPrefix, m.StackID, markerOpenSuffix)
	fmt.Fprintf(&b, "**Stack** (`%s`):\n\n", m.StackID)

	if len(m.Nodes) == 0 {
		b.WriteString("_no members_\n")
	} else {
		// Map keys -> PR numbers for parent links.
		prByKey := make(map[string]int, len(m.Nodes))
		branchByKey := make(map[string]string, len(m.Nodes))
		for _, n := range m.Nodes {
			prByKey[n.Key] = n.PRNumber
			branchByKey[n.Key] = n.Branch
		}

		for _, n := range m.Nodes {
			isSelf := n.Key == m.Self
			line := renderNodeLine(n, prByKey, branchByKey)
			if isSelf {
				fmt.Fprintf(&b, "- **%s** ← this PR\n", line)
			} else {
				fmt.Fprintf(&b, "- %s\n", line)
			}
		}
	}

	b.WriteString("\n_Generated by `wgo stack`. Edit text above or below this block, not inside it._\n")
	b.WriteString(markerClose)
	return b.String()
}

func renderNodeLine(n MarkerNode, prByKey map[string]int, branchByKey map[string]string) string {
	var sb strings.Builder
	if n.PRNumber > 0 {
		fmt.Fprintf(&sb, "#%d %s", n.PRNumber, n.Branch)
	} else {
		fmt.Fprintf(&sb, "%s _(no PR)_", n.Branch)
	}

	// Stable parent display: only in-stack parents (those we know branches for),
	// sorted by branch name for determinism.
	var parentLabels []string
	for _, pk := range n.Parents {
		branch, known := branchByKey[pk]
		if !known {
			continue
		}
		if num, ok := prByKey[pk]; ok && num > 0 {
			parentLabels = append(parentLabels, fmt.Sprintf("#%d", num))
		} else {
			parentLabels = append(parentLabels, branch)
		}
	}
	sort.Strings(parentLabels)
	switch len(parentLabels) {
	case 0:
		sb.WriteString(" ← root")
	case 1:
		fmt.Fprintf(&sb, " ↳ on %s", parentLabels[0])
	default:
		fmt.Fprintf(&sb, " ↳ on %s", strings.Join(parentLabels, " + "))
	}
	return sb.String()
}

// ApplyMarker inserts (or replaces) the marker block in `body`. If the body
// has no existing marker, the new block is appended with a blank-line
// separator. Returns the updated body.
func ApplyMarker(body, rendered string) string {
	if markerBlockPattern.MatchString(body) {
		return markerBlockPattern.ReplaceAllString(body, regexReplaceLiteral(rendered))
	}
	body = strings.TrimRight(body, "\n")
	if body == "" {
		return rendered + "\n"
	}
	return body + "\n\n" + rendered + "\n"
}

// StripMarker removes any wgo-stack block from the body, leaving surrounding
// text intact. Used when removing a branch from a stack.
func StripMarker(body string) string {
	stripped := markerBlockPattern.ReplaceAllString(body, "")
	// Collapse the blank-line pair we likely left behind.
	stripped = regexp.MustCompile(`\n{3,}`).ReplaceAllString(stripped, "\n\n")
	return strings.TrimRight(stripped, "\n") + "\n"
}

// ExtractStackID returns the stack id from any marker block in `body`,
// or "" if no well-formed block is present.
func ExtractStackID(body string) string {
	block := markerBlockPattern.FindString(body)
	if block == "" {
		return ""
	}
	// "<!-- wgo-stack:ID -->"
	_, rest, ok := strings.Cut(block, markerOpenPrefix)
	if !ok {
		return ""
	}
	id, _, ok := strings.Cut(rest, markerOpenSuffix)
	if !ok {
		return ""
	}
	return strings.TrimSpace(id)
}

// regexReplaceLiteral escapes `$` so the replacement is treated literally
// by regexp.ReplaceAllString.
func regexReplaceLiteral(s string) string {
	return strings.ReplaceAll(s, "$", "$$")
}
